python test.py \
 --image_dir data/iu_xray/images/ \
 --ann_path data/iu_xray/annotation.json \
 --dataset_name iu_xray \
 --max_seq_length 60 \
 --threshold 3 \
 --batch_size 16 \
 --epochs 100 \
 --save_dir results/iu_xray \
 --step_size 10\
 --gamma 0.8 \
 --log_period 50 \
 --seed 7580 \
 --lr_ve 1e-4 \
 --lr_ed 5e-4 \
 --cmm_size 2048 \
 --cmm_dim 512 \
 --beam_size 3 \
 --topk 32 \
 --num_layers 3 \
 --load model_best.pth
 